# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@5.0.3
  cypress: cypress-io/cypress@2.2.0

jobs:
  build-and-run:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run build
      - run:
          command: npm run start

workflows:
  test:
    jobs:
      - node/test
  run-next-server:
    jobs:
      - build-and-run
  e2e:
    jobs:
      - cypress/run:
          wait-on: 'http://localhost:3000'
